import Head from 'next/head'
import { Layout } from '@/components/Layout'
import { MainSection } from '@/components/MainSection'
import { ProfileSection } from '@/components/PofileSection'

export default function Home() {
    return (
        <>
            <Head>
                <title>TURNOS MENDOZA</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <Layout>
                    <MainSection></MainSection>
                    <ProfileSection></ProfileSection>
                </Layout>
            </main>
        </>
    )
}
